{
  for (  Callback<R> cb : this.successCallbacks) {
    try {
      EventRecord.caller(cb.getClass(),EventType.CALLBACK_LISTENER,"fire(" + response.getClass().getSimpleName() + ")").debug();
      cb.fire(response);
    }
 catch (    Throwable t) {
      LOG.error("Exception occurred while trying to call: " + cb.getClass().getSimpleName() + ".apply( "+ t.getMessage()+ " )");
      LOG.error(t,t);
    }
  }
}
