{
  EventRecord.here(CallbackListenerSequence.class,EventType.CALLBACK,"fire(" + response.getClass().getName() + ")").debug();
  for (  Callback<R> cb : this.successCallbacks) {
    try {
      EventRecord.here(this.getClass(),EventType.CALLBACK,cb.getClass(),"fire(" + response.getClass().getCanonicalName() + ")").debug();
      cb.fire(response);
    }
 catch (    Throwable t) {
      LOG.error("Exception occurred while trying to call: " + cb.getClass() + ".apply( "+ t.getMessage()+ " )");
      LOG.error(t,t);
    }
  }
}
