{
  try {
    arg0.stop();
  }
 catch (  Exception ex) {
    LOG.error(ex,ex);
  }
  return true;
}
