{
  R reply=null;
  Throwable failure=null;
  try {
    reply=this.future.get();
  }
 catch (  Throwable t) {
    LOG.error(t,t);
    failure=t;
  }
  if (reply != null) {
    try {
      EventRecord.caller(this.getClass(),EventType.CALLBACK,"fire(" + reply.getClass().getSimpleName() + ")").trace();
      this.callback.fire(reply);
    }
 catch (    Throwable t) {
      LOG.error(t,t);
      failure=t;
    }
  }
 else   if (failure != null) {
    this.doFail(failure);
  }
 else {
    LOG.warn("Ignoring application of callback " + this.getClass().getSimpleName() + " since reply is: "+ reply);
    Exceptions.eat("Callback marked as done has null valued response: " + reply);
  }
}
