def error(self, msg):
    print ('Error: %s' % msg)
    sys.exit(1)
