{
  Throwable t=exceptionEvent.getCause();
  if (t != null && IOException.class.isAssignableFrom(t.getClass())) {
    LOG.error(t,t);
    ctx.getChannel().close();
  }
 else {
    this.exceptionCaught(t);
  }
}
