{
  try {
    Throwable fin=t;
    if (t instanceof ExecutionException) {
      fin=t.getCause() != null ? t.getCause() : t;
    }
    LOG.error(t);
    if (Exceptions.isCausedBy(t,InterruptedException.class)) {
      Thread.currentThread().interrupt();
    }
 else     if (Exceptions.isCausedBy(t,FailedRequestException.class)) {
      Logs.extreme().debug(fin,fin);
      this.pendingErrors.add(fin);
    }
 else     if (Exceptions.isCausedBy(t,JiBXException.class)) {
      Logs.extreme().debug(fin,fin);
      this.pendingErrors.add(fin);
    }
 else     if (Exceptions.isCausedBy(t,ConnectionException.class) || Exceptions.isCausedBy(t,IOException.class)) {
      LOG.error(this.getName() + ": Error communicating with cluster: " + fin.getMessage());
      Logs.extreme().debug(fin,fin);
      this.pendingErrors.add(fin);
    }
 else {
      Logs.extreme().debug(fin,fin);
      this.pendingErrors.add(fin);
    }
  }
 catch (  Exception ex) {
    LOG.error(ex,ex);
  }
  return false;
}
