{
  EventRecord.caller(this.getClass(),EventType.TRANSITION_FUTURE,"setException(" + exception.getClass().getCanonicalName() + "): "+ exception.getMessage()).trace();
  boolean r=false;
  if (!(r=super.setException(exception))) {
    LOG.error("Duplicate exception: " + exception.getMessage());
  }
  return r;
}
