{
  Map<String,Set<String>> accountingGroups=null;
  Map<String,Set<String>> groups=null;
  Map<String,Map<String,String>> users=null;
  LdapClient ldap=null;
  try {
    ldap=LdapClient.authenticateClient(lic);
    if (lic.hasAccountingGroups()) {
      accountingGroups=loadLdapGroupType(ldap,lic.getAccountingGroupBaseDn(),lic.getAccountingGroupIdAttribute(),lic.getGroupsAttribute(),lic.getGroupIdAttribute(),lic.getAccountingGroupsSelection());
    }
    groups=loadLdapGroupType(ldap,lic.getGroupBaseDn(),lic.getGroupIdAttribute(),lic.getUsersAttribute(),lic.getUserIdAttribute(),lic.getGroupsSelection());
    users=loadLdapUsers(ldap,lic);
  }
 catch (  Exception e) {
    LOG.error(e,e);
    LOG.error("Failed to sync with LDAP",e);
    return;
  }
 finally {
    if (ldap != null) {
      ldap.close();
    }
  }
  if (!lic.hasAccountingGroups()) {
    accountingGroups=lic.getGroupsPartition();
  }
  if (VERBOSE) {
    LOG.debug("Sync remote accounts: " + accountingGroups);
    LOG.debug("Sync remote groups: " + groups);
    LOG.debug("Sync remote users: " + users);
  }
  checkConflictingIdentities(accountingGroups,groups,users);
  rebuildLocalAuthDatabase(lic,accountingGroups,groups,users);
}
